# Generated by Django 4.0 on 2022-05-03 04:14

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_myuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', account.models.MyUserManager()),
            ],
        ),
    ]
